[package]
name = "performance"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="performance_rust"
path = "src-tauri/lib.rs"
crate-type = ["cdylib"]
bench = false

[dependencies]
