[package]
name = "performance"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[lib]
#name="performance_rust"
#path = "src-tauri/lib.rs"
#crate-type = ["cdylib"]
#bench = false

[[bin]]
name="performance_rust"
path = "src-tauri/main.rs"

[dependencies]
reqwest = "0.11.11"
futures = "0.3.21"
tokio = { version = "1.19.2", features = ["full"] }
serde = "1.0.137"
serde_json = "1.0.82"