name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Build Essentials
        run: sudo apt-get update && sudo apt install build-essential && sudo apt-get install manpages-dev
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install Lerna globally
        run: yarn global add lerna
      - name: Enable workspaces in Yarn
        run: yarn config set workspaces-experimental true
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Build Packages and Install dependencies
        run: yarn run build
      - name: Run Playwright tests
        run: export HEADLESS=true && npx playwright test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
